---
#
#  PLUGIN BY:
#   _    __                  _                                     _
#  | |  / /                 | |                                   | |
#  | | / /                  | |                                   | |
#  | |/ / _   _  ____   ____| | ______ ____   _____ ______   ____ | | __
#  | |\ \| | | |/ __ \ / __ \ |/ /  __/ __ \ / __  | _  _ \ / __ \| |/ /
#  | | \ \ \_| | <__> |  ___/   <| / | <__> | <__| | |\ |\ | <__> |   <
#  |_|  \_\__  |\___  |\____|_|\_\_|  \____^_\___  |_||_||_|\____^_\|\_\
#            | |    | |                          | |
#         ___/ | ___/ |                          | |
#        |____/ |____/                           |_|
#
# A PocketMine-MP plugin that allows players to use tags
# Copyright (C) 2020-2021 Kygekraqmak
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# he Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#

name: KygekTagsShop
version: 1.0.0-RC2
main: Kygekraqmak\KygekTagsShop\TagsShop
api: 4.0.0
author: Kygekraqmak
website: "https://github.com/thebigcrafter/KygekTagsShop"
softdepend: BedrockEconomy

permissions:
  kygektagsshop.tags:
    description: Allows player to use KygekTagsShop to buy and sell tags
    default: true
...
